spring:
  application:
    name: maintainer
  
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
  
  jdbc:
    template:
      query-timeout: 30s

  threads:
    virtual:
      enabled: true

logging:
  level:
    com.example.maintainer: DEBUG
    org.springframework.jdbc: DEBUG